# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/3DCV_projects/HyenaIP/HyenaIP/Forms/ImageProcessing/imageprocessing.ui'
#
# Created: Tue Feb 24 17:50:00 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageProcessing(object):
    def setupUi(self, ImageProcessing):
        ImageProcessing.setObjectName(_fromUtf8("ImageProcessing"))
        ImageProcessing.resize(1280, 1024)
        ImageProcessing.setMinimumSize(QtCore.QSize(1280, 1024))
        ImageProcessing.setMaximumSize(QtCore.QSize(1280, 1024))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        ImageProcessing.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../Media/Images/HyenaLogo.gif")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImageProcessing.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(ImageProcessing)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.ListPackages = QtGui.QListWidget(self.centralWidget)
        self.ListPackages.setGeometry(QtCore.QRect(10, 70, 311, 701))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ListPackages.setFont(font)
        self.ListPackages.setObjectName(_fromUtf8("ListPackages"))
        item = QtGui.QListWidgetItem()
        self.ListPackages.addItem(item)
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 321, 61))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 800, 701, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.BtnRunAndAddNewPackage = QtGui.QPushButton(self.groupBox)
        self.BtnRunAndAddNewPackage.setGeometry(QtCore.QRect(360, 70, 321, 50))
        self.BtnRunAndAddNewPackage.setObjectName(_fromUtf8("BtnRunAndAddNewPackage"))
        self.LineNameNewPackage = QtGui.QLineEdit(self.groupBox)
        self.LineNameNewPackage.setGeometry(QtCore.QRect(70, 30, 611, 31))
        self.LineNameNewPackage.setText(_fromUtf8(""))
        self.LineNameNewPackage.setObjectName(_fromUtf8("LineNameNewPackage"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(340, 70, 371, 701))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 50, 321, 111))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.Sb_Height = QtGui.QSpinBox(self.groupBox_5)
        self.Sb_Height.setGeometry(QtCore.QRect(94, 40, 121, 25))
        self.Sb_Height.setMaximum(99999)
        self.Sb_Height.setObjectName(_fromUtf8("Sb_Height"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setGeometry(QtCore.QRect(20, 40, 91, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 91, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Sb_Width = QtGui.QSpinBox(self.groupBox_5)
        self.Sb_Width.setGeometry(QtCore.QRect(94, 70, 121, 25))
        self.Sb_Width.setMaximum(99999)
        self.Sb_Width.setObjectName(_fromUtf8("Sb_Width"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 170, 321, 401))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.Cb_Laplacian = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Laplacian.setGeometry(QtCore.QRect(20, 40, 111, 20))
        self.Cb_Laplacian.setObjectName(_fromUtf8("Cb_Laplacian"))
        self.Cb_Smooth = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Smooth.setGeometry(QtCore.QRect(20, 80, 111, 20))
        self.Cb_Smooth.setObjectName(_fromUtf8("Cb_Smooth"))
        self.Sl_Smooth = QtGui.QSlider(self.groupBox_6)
        self.Sl_Smooth.setGeometry(QtCore.QRect(140, 80, 160, 22))
        self.Sl_Smooth.setMinimum(1)
        self.Sl_Smooth.setMaximum(15)
        self.Sl_Smooth.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_Smooth.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_Smooth.setTickInterval(1)
        self.Sl_Smooth.setObjectName(_fromUtf8("Sl_Smooth"))
        self.Cb_Sobel_X = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Sobel_X.setGeometry(QtCore.QRect(20, 120, 111, 20))
        self.Cb_Sobel_X.setObjectName(_fromUtf8("Cb_Sobel_X"))
        self.Sl_Sobel_X = QtGui.QSlider(self.groupBox_6)
        self.Sl_Sobel_X.setGeometry(QtCore.QRect(140, 120, 160, 22))
        self.Sl_Sobel_X.setMinimum(1)
        self.Sl_Sobel_X.setMaximum(30)
        self.Sl_Sobel_X.setSingleStep(2)
        self.Sl_Sobel_X.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_Sobel_X.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_Sobel_X.setTickInterval(5)
        self.Sl_Sobel_X.setObjectName(_fromUtf8("Sl_Sobel_X"))
        self.Sl_Sobel_Y = QtGui.QSlider(self.groupBox_6)
        self.Sl_Sobel_Y.setGeometry(QtCore.QRect(140, 160, 160, 22))
        self.Sl_Sobel_Y.setMinimum(1)
        self.Sl_Sobel_Y.setMaximum(30)
        self.Sl_Sobel_Y.setSingleStep(2)
        self.Sl_Sobel_Y.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_Sobel_Y.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_Sobel_Y.setTickInterval(5)
        self.Sl_Sobel_Y.setObjectName(_fromUtf8("Sl_Sobel_Y"))
        self.Cb_Sobel_Y = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Sobel_Y.setGeometry(QtCore.QRect(20, 160, 111, 20))
        self.Cb_Sobel_Y.setObjectName(_fromUtf8("Cb_Sobel_Y"))
        self.Sl_Erosion = QtGui.QSlider(self.groupBox_6)
        self.Sl_Erosion.setGeometry(QtCore.QRect(140, 200, 160, 22))
        self.Sl_Erosion.setMinimum(1)
        self.Sl_Erosion.setMaximum(30)
        self.Sl_Erosion.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_Erosion.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_Erosion.setTickInterval(5)
        self.Sl_Erosion.setObjectName(_fromUtf8("Sl_Erosion"))
        self.Cb_Erosion = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Erosion.setGeometry(QtCore.QRect(20, 200, 111, 20))
        self.Cb_Erosion.setObjectName(_fromUtf8("Cb_Erosion"))
        self.Sl_Dilation = QtGui.QSlider(self.groupBox_6)
        self.Sl_Dilation.setGeometry(QtCore.QRect(140, 240, 160, 22))
        self.Sl_Dilation.setMinimum(1)
        self.Sl_Dilation.setMaximum(50)
        self.Sl_Dilation.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_Dilation.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_Dilation.setTickInterval(5)
        self.Sl_Dilation.setObjectName(_fromUtf8("Sl_Dilation"))
        self.Cb_Dilation = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_Dilation.setGeometry(QtCore.QRect(20, 240, 111, 20))
        self.Cb_Dilation.setObjectName(_fromUtf8("Cb_Dilation"))
        self.Cb_MorphologicalGradient = QtGui.QCheckBox(self.groupBox_6)
        self.Cb_MorphologicalGradient.setGeometry(QtCore.QRect(20, 280, 111, 20))
        self.Cb_MorphologicalGradient.setObjectName(_fromUtf8("Cb_MorphologicalGradient"))
        self.Sl_MorphologicalGradient = QtGui.QSlider(self.groupBox_6)
        self.Sl_MorphologicalGradient.setGeometry(QtCore.QRect(140, 280, 160, 22))
        self.Sl_MorphologicalGradient.setMinimum(1)
        self.Sl_MorphologicalGradient.setMaximum(50)
        self.Sl_MorphologicalGradient.setOrientation(QtCore.Qt.Horizontal)
        self.Sl_MorphologicalGradient.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Sl_MorphologicalGradient.setTickInterval(5)
        self.Sl_MorphologicalGradient.setObjectName(_fromUtf8("Sl_MorphologicalGradient"))
        self.Cb_EnableColorShape = QtGui.QCheckBox(self.tab)
        self.Cb_EnableColorShape.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.Cb_EnableColorShape.setFont(font)
        self.Cb_EnableColorShape.setTristate(False)
        self.Cb_EnableColorShape.setObjectName(_fromUtf8("Cb_EnableColorShape"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName(_fromUtf8("tabWidgetPage1"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabWidgetPage1)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 321, 361))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.Cb_BINARY = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_BINARY.setGeometry(QtCore.QRect(10, 110, 111, 21))
        self.Cb_BINARY.setObjectName(_fromUtf8("Cb_BINARY"))
        self.Cb_BINARY_INV = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_BINARY_INV.setGeometry(QtCore.QRect(10, 140, 141, 23))
        self.Cb_BINARY_INV.setObjectName(_fromUtf8("Cb_BINARY_INV"))
        self.Cb_TRUNC = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_TRUNC.setGeometry(QtCore.QRect(10, 170, 101, 23))
        self.Cb_TRUNC.setObjectName(_fromUtf8("Cb_TRUNC"))
        self.Cb_TOZERO = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_TOZERO.setGeometry(QtCore.QRect(10, 200, 101, 23))
        self.Cb_TOZERO.setObjectName(_fromUtf8("Cb_TOZERO"))
        self.Cb_OTSU = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_OTSU.setGeometry(QtCore.QRect(10, 320, 271, 23))
        self.Cb_OTSU.setObjectName(_fromUtf8("Cb_OTSU"))
        self.Cb_ADAP_MEAN = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_ADAP_MEAN.setGeometry(QtCore.QRect(10, 260, 261, 23))
        self.Cb_ADAP_MEAN.setObjectName(_fromUtf8("Cb_ADAP_MEAN"))
        self.Cb_ADAP_GAUSSIAN = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_ADAP_GAUSSIAN.setGeometry(QtCore.QRect(10, 290, 281, 23))
        self.Cb_ADAP_GAUSSIAN.setObjectName(_fromUtf8("Cb_ADAP_GAUSSIAN"))
        self.Cb_TOZERO_INV = QtGui.QCheckBox(self.groupBox_4)
        self.Cb_TOZERO_INV.setGeometry(QtCore.QRect(10, 230, 141, 21))
        self.Cb_TOZERO_INV.setObjectName(_fromUtf8("Cb_TOZERO_INV"))
        self.Hs_LevelThreshold = QtGui.QSlider(self.groupBox_4)
        self.Hs_LevelThreshold.setGeometry(QtCore.QRect(10, 30, 291, 61))
        self.Hs_LevelThreshold.setMaximum(250)
        self.Hs_LevelThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.Hs_LevelThreshold.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Hs_LevelThreshold.setObjectName(_fromUtf8("Hs_LevelThreshold"))
        self.Cb_EnableThresholding = QtGui.QCheckBox(self.tabWidgetPage1)
        self.Cb_EnableThresholding.setGeometry(QtCore.QRect(10, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.Cb_EnableThresholding.setFont(font)
        self.Cb_EnableThresholding.setTristate(False)
        self.Cb_EnableThresholding.setObjectName(_fromUtf8("Cb_EnableThresholding"))
        self.tabWidget.addTab(self.tabWidgetPage1, _fromUtf8(""))
        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName(_fromUtf8("tabWidgetPage2"))
        self.Cb_EnableCannyEdges = QtGui.QCheckBox(self.tabWidgetPage2)
        self.Cb_EnableCannyEdges.setGeometry(QtCore.QRect(10, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.Cb_EnableCannyEdges.setFont(font)
        self.Cb_EnableCannyEdges.setTristate(False)
        self.Cb_EnableCannyEdges.setObjectName(_fromUtf8("Cb_EnableCannyEdges"))
        self.groupBox_7 = QtGui.QGroupBox(self.tabWidgetPage2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 60, 321, 281))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_7)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Hs_CannyThreshold = QtGui.QSlider(self.groupBox_7)
        self.Hs_CannyThreshold.setGeometry(QtCore.QRect(10, 70, 291, 61))
        self.Hs_CannyThreshold.setMaximum(200)
        self.Hs_CannyThreshold.setOrientation(QtCore.Qt.Horizontal)
        self.Hs_CannyThreshold.setInvertedControls(False)
        self.Hs_CannyThreshold.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Hs_CannyThreshold.setObjectName(_fromUtf8("Hs_CannyThreshold"))
        self.Hs_CannyLinks = QtGui.QSlider(self.groupBox_7)
        self.Hs_CannyLinks.setGeometry(QtCore.QRect(10, 180, 291, 61))
        self.Hs_CannyLinks.setMaximum(200)
        self.Hs_CannyLinks.setOrientation(QtCore.Qt.Horizontal)
        self.Hs_CannyLinks.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.Hs_CannyLinks.setObjectName(_fromUtf8("Hs_CannyLinks"))
        self.label_9 = QtGui.QLabel(self.groupBox_7)
        self.label_9.setGeometry(QtCore.QRect(10, 150, 251, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tabWidgetPage2, _fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(730, 490, 530, 450))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.Lb_ImageFiltered = QtGui.QLabel(self.groupBox_3)
        self.Lb_ImageFiltered.setGeometry(QtCore.QRect(10, 20, 511, 421))
        self.Lb_ImageFiltered.setText(_fromUtf8(""))
        self.Lb_ImageFiltered.setPixmap(QtGui.QPixmap(_fromUtf8("../../Media/Images/HyenaLogo.gif")))
        self.Lb_ImageFiltered.setAlignment(QtCore.Qt.AlignCenter)
        self.Lb_ImageFiltered.setObjectName(_fromUtf8("Lb_ImageFiltered"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(730, 20, 530, 450))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Lb_ImageOriginal = QtGui.QLabel(self.groupBox_2)
        self.Lb_ImageOriginal.setGeometry(QtCore.QRect(7, 28, 511, 411))
        self.Lb_ImageOriginal.setText(_fromUtf8(""))
        self.Lb_ImageOriginal.setPixmap(QtGui.QPixmap(_fromUtf8("../../Media/Images/HyenaLogo.gif")))
        self.Lb_ImageOriginal.setAlignment(QtCore.Qt.AlignCenter)
        self.Lb_ImageOriginal.setObjectName(_fromUtf8("Lb_ImageOriginal"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(340, 10, 321, 61))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        ImageProcessing.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(ImageProcessing)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        ImageProcessing.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(ImageProcessing)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        ImageProcessing.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(ImageProcessing)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        ImageProcessing.setStatusBar(self.statusBar)
        self.actionClose_Module = QtGui.QAction(ImageProcessing)
        self.actionClose_Module.setObjectName(_fromUtf8("actionClose_Module"))
        self.actionLicense = QtGui.QAction(ImageProcessing)
        self.actionLicense.setObjectName(_fromUtf8("actionLicense"))
        self.menuFile.addAction(self.actionClose_Module)
        self.menuAbout.addAction(self.actionLicense)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(ImageProcessing)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageProcessing)

    def retranslateUi(self, ImageProcessing):
        ImageProcessing.setWindowTitle(_translate("ImageProcessing", "Hyena - Image Processing Module", None))
        self.ListPackages.setSortingEnabled(True)
        __sortingEnabled = self.ListPackages.isSortingEnabled()
        self.ListPackages.setSortingEnabled(False)
        item = self.ListPackages.item(0)
        item.setText(_translate("ImageProcessing", "No packages found", None))
        self.ListPackages.setSortingEnabled(__sortingEnabled)
        self.label_4.setText(_translate("ImageProcessing", "<html><head/><body><p><span style=\" font-weight:600;\">1. Select the INPUT package</span></p></body></html>", None))
        self.groupBox.setTitle(_translate("ImageProcessing", "Output settings", None))
        self.BtnRunAndAddNewPackage.setText(_translate("ImageProcessing", "3. Process  new package", None))
        self.label_2.setText(_translate("ImageProcessing", "Name:", None))
        self.groupBox_5.setTitle(_translate("ImageProcessing", "Resize", None))
        self.label.setText(_translate("ImageProcessing", "Height", None))
        self.label_3.setText(_translate("ImageProcessing", "Width", None))
        self.groupBox_6.setTitle(_translate("ImageProcessing", "Color", None))
        self.Cb_Laplacian.setText(_translate("ImageProcessing", "Laplacian", None))
        self.Cb_Smooth.setText(_translate("ImageProcessing", "Smooth", None))
        self.Cb_Sobel_X.setText(_translate("ImageProcessing", "Sobel X", None))
        self.Cb_Sobel_Y.setText(_translate("ImageProcessing", "Sobel Y", None))
        self.Cb_Erosion.setText(_translate("ImageProcessing", "Erosion", None))
        self.Cb_Dilation.setText(_translate("ImageProcessing", "Dilation", None))
        self.Cb_MorphologicalGradient.setText(_translate("ImageProcessing", "Morph. Grad.", None))
        self.Cb_EnableColorShape.setText(_translate("ImageProcessing", "Enable Color/shape changes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ImageProcessing", "Color/shape", None))
        self.groupBox_4.setTitle(_translate("ImageProcessing", "Options", None))
        self.Cb_BINARY.setText(_translate("ImageProcessing", "BINARY", None))
        self.Cb_BINARY_INV.setText(_translate("ImageProcessing", "BINARY_INV", None))
        self.Cb_TRUNC.setText(_translate("ImageProcessing", "TRUNC", None))
        self.Cb_TOZERO.setText(_translate("ImageProcessing", "TOZERO", None))
        self.Cb_OTSU.setText(_translate("ImageProcessing", "THRESH_OTSU", None))
        self.Cb_ADAP_MEAN.setText(_translate("ImageProcessing", "ADAPTIVE_THRESH_MEAN", None))
        self.Cb_ADAP_GAUSSIAN.setText(_translate("ImageProcessing", "ADAPTIVE_THRESH_GAUSSIAN", None))
        self.Cb_TOZERO_INV.setText(_translate("ImageProcessing", "TOZERO_INV", None))
        self.Cb_EnableThresholding.setText(_translate("ImageProcessing", "Enable Thresholding", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("ImageProcessing", "Thresholding", None))
        self.Cb_EnableCannyEdges.setText(_translate("ImageProcessing", "Enable Canny edges", None))
        self.groupBox_7.setTitle(_translate("ImageProcessing", "Options", None))
        self.label_8.setText(_translate("ImageProcessing", "Threshold level:", None))
        self.label_9.setText(_translate("ImageProcessing", "Threshold links:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("ImageProcessing", "Canny edges", None))
        self.groupBox_3.setTitle(_translate("ImageProcessing", "Filtered Image", None))
        self.groupBox_2.setTitle(_translate("ImageProcessing", "Original Image", None))
        self.label_7.setText(_translate("ImageProcessing", "<html><head/><body><p><span style=\" font-weight:600;\">2. Select and combine filters bellow</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("ImageProcessing", "File", None))
        self.menuAbout.setTitle(_translate("ImageProcessing", "About", None))
        self.actionClose_Module.setText(_translate("ImageProcessing", "Close Module", None))
        self.actionLicense.setText(_translate("ImageProcessing", "License", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ImageProcessing = QtGui.QMainWindow()
    ui = Ui_ImageProcessing()
    ui.setupUi(ImageProcessing)
    ImageProcessing.show()
    sys.exit(app.exec_())

